# Generated by Django 5.0.6 on 2024-06-07 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_user_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentWiseUser',
            fields=[
                ('depuserid', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
        ),
    ]
