# Generated by Django 5.0.6 on 2024-06-03 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImages',
            fields=[
                ('imgid', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.ImageField(upload_to='user_images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
        ),
    ]
