# Generated by Django 5.0.6 on 2024-06-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_user_name_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentid', models.AutoField(primary_key=True, serialize=False)),
                ('departmentname', models.CharField(max_length=100)),
            ],
        ),
    ]
